In [2]:
import numpy as np

In [32]:
a1=np.array([[1,2,3],
             [4,5,6],
             [7,8,9]])
             
a2=np.array ([[10,13,12],
             [19,17,15],
             [16,14,18]])


In [33]:
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
a2

array([[10, 13, 12],
       [19, 17, 15],
       [16, 14, 18]])

## Concatenation of two arrays

In [35]:
concate = np.concatenate((a1, a2))
concate

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 13, 12],
       [19, 17, 15],
       [16, 14, 18]])

## Reshape the generated one dimensional array .

In [36]:
a3=np.array ([[10,11],
             [13,14],
             [16,17]])

In [37]:
reshape=a3.reshape(2,3)
reshape

array([[10, 11, 13],
       [14, 16, 17]])

## Apply minimum of two numpy universal functions on two original arrays.

In [38]:
mini = np.min(a3)
mini

10

In [39]:
maxi = np.max(a3)
maxi

17

## Find maximum value from A array and minimum value from B array

In [40]:
mini1 = np.min(a2)
mini1


10

In [41]:
maxi2 = np.max(a1)
maxi2

9

## Apply sort and argsort on B array.

In [42]:
sort=np.sort(a2)
sort

array([[10, 12, 13],
       [15, 17, 19],
       [14, 16, 18]])

In [43]:
s = np.argsort(a2)
s

array([[0, 2, 1],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)