In [1]:
import numpy as np

## 1. Distance Calculation

In [2]:
import math 
  
# Function to calculate distance 
def distance(x1 , y1 , x2 , y2): 
  
    # Calculating distance 
    return math.sqrt(math.pow(x2 - x1, 2) +
                math.pow(y2 - y1, 2) * 1.0) 
  
# Drivers Code 
print("Enter value of X1, X2, Y1, Y2\n")
xx1 = int(input("X1: "))
xx2 = int(input("X2: "))
yy1 = int(input("Y1: "))
yy2 = int(input("Y2: "))
print("\nThe distance is: %.6f"%distance(xx1, yy1, xx2, yy2)) 

Enter value of X1, X2, Y1, Y2

X1: 5
X2: 7
Y1: 6
Y2: 14

The distance is: 8.246211


### NumPy Array

In [3]:
a1=np.array([[1,5,3],
             [4,9,78],
             [23,0,12]])
             
a2=np.array ([[10,13,12],
             [19,17,15],
             [16,14,18]])

In [4]:
a1

array([[ 1,  5,  3],
       [ 4,  9, 78],
       [23,  0, 12]])

In [5]:
a2

array([[10, 13, 12],
       [19, 17, 15],
       [16, 14, 18]])

## 2. Slicing The Array 

In [6]:
sliArr = np.array([1, 2, 3, 4, 5, 6, 7])

print(sliArr[1:5])

[2 3 4 5]


## 3. Reshaping The Array 

In [7]:
a3=np.array ([[10,11],
             [13,14],
             [16,17]])

In [8]:
a3.shape

(3, 2)

In [9]:
a2*a3

ValueError: operands could not be broadcast together with shapes (3,3) (3,2) 

In [10]:
a3= a3.reshape(2,3,1)

In [11]:
a3

array([[[10],
        [11],
        [13]],

       [[14],
        [16],
        [17]]])

In [12]:
a2*a3

array([[[100, 130, 120],
        [209, 187, 165],
        [208, 182, 234]],

       [[140, 182, 168],
        [304, 272, 240],
        [272, 238, 306]]])

## 4. Concatenation And Split of two arrays

In [13]:
concate = np.concatenate((a1, a2))
print(concate)

[[ 1  5  3]
 [ 4  9 78]
 [23  0 12]
 [10 13 12]
 [19 17 15]
 [16 14 18]]


In [14]:
split = np.array_split(concate, 2)
print(split[0])
print(split[1])

[[ 1  5  3]
 [ 4  9 78]
 [23  0 12]]
[[10 13 12]
 [19 17 15]
 [16 14 18]]


## 5. Arithemic Operations

In [15]:
mean=np.mean(a2)
mean

14.88888888888889

In [16]:
std=np.std(a2)
std

2.7666443551086073

In [17]:
var=np.var(a2)
var

7.65432098765432

## 6. Find maximum value from A array and minimum value from B array

In [18]:
mini1 = np.min(a2)
mini1

10

In [19]:
maxi2 = np.max(a1)
maxi2

78

In [20]:
median = np.median(a2)
median

15.0

## 7. More With NumPy

In [21]:
#transpose of numPy
transpose = a1.T
transpose

array([[ 1,  4, 23],
       [ 5,  9,  0],
       [ 3, 78, 12]])

In [22]:
#sorting NumPyarray
sort=np.sort(a2)
sort

array([[10, 12, 13],
       [15, 17, 19],
       [14, 16, 18]])

In [23]:
a2

array([[10, 13, 12],
       [19, 17, 15],
       [16, 14, 18]])

In [25]:
#argsorting
s = np.argsort(a2)
s

array([[0, 2, 1],
       [2, 1, 0],
       [1, 0, 2]], dtype=int64)

In [26]:
x = np.array([3, 1, 2])
np.argsort(x)

array([1, 2, 0], dtype=int64)